name: demo-action




on:

  issues:

    types: opened 




    

  workflow_dispatch:  

  # push:

   # branches: main

   




jobs:

  build:

    runs-on: ubuntu-latest

    steps:

     - uses: actions/checkout@v4




     - name: run a sample

       run: echo Hello,world!
